apiVersion: v1
kind: Service
metadata:
  name: gql-service-user
spec:
  selector:
    app: gql-service-user
  ports:
  - port: 3001
    protocol: TCP
    type: NodePort 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gql-service-user
spec:
  selector:
    matchLabels:
      app: gql-service-user
  replicas: 2
  template:
    metadata:
      labels:
        app: gql-service-user
    spec:
      containers:
      - name: gql-service-user
        image: gigihsigap/gql-service-user # Dockerhub
        ports:
        - containerPort: 3001
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: gql-service-media
spec:
  selector:
    app: gql-service-media
  ports:
  - port: 3002
    protocol: TCP
    type: NodePort 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gql-service-media
spec:
  selector:
    matchLabels:
      app: gql-service-media
  replicas: 2
  template:
    metadata:
      labels:
        app: gql-service-media
    spec:
      containers:
      - name: gql-service-media
        image: gigihsigap/gql-service-media # Dockerhub
        ports:
        - containerPort: 3002
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
