name: Dev - Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      subgraph_name:
        type: choice
        description: Select service name
        required: true
        options:
        - user-dev
        - media-dev

env:
  ENVIRONMENT: 'dev'
  APP_NAME: 'gql-service'

jobs:
  dev_build_stage:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (User)
        if: ${{ inputs.subgraph_name == 'user-dev' }}
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          file: user.Dockerfile
          push: true
          tags: |
            gigihsigap/${{env.APP_NAME}}-user:${{ github.run_number }}
      
      - name: Build and push (Media)
        if: ${{ inputs.subgraph_name == 'media-dev' }}
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          file: media.Dockerfile
          push: true
          tags: |
            gigihsigap/${{env.APP_NAME}}-media:${{ github.run_number }}

      - name: Discord notification
        if: failure()
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Build for '${{env.APP_NAME}} - ${{env.ENVIRONMENT}}' FAILED! :x:"
      
  dev_deploy_stage:
    name: Deploy
    needs: dev_build_stage
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands (User)
        if: ${{ inputs.subgraph_name == 'user-dev' }}
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 34.128.98.253
          username: gap
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin ${{ secrets.DOCKERHUB_TOKEN }} &&
            sudo docker ps -aq | xargs -I {} sudo docker stop {} &&
            sudo docker ps -aq | xargs -I {} sudo docker rm {} &&
            sudo docker run -d -p 3001:3001 gigihsigap/${{env.APP_NAME}}-user:${{ github.run_number }}
      
      - name: Executing remote ssh commands (Media)
        if: ${{ inputs.subgraph_name == 'media-dev' }}
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 34.101.58.10
          username: gap
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin ${{ secrets.DOCKERHUB_TOKEN }} &&
            sudo docker ps -aq | xargs -I {} sudo docker stop {} &&
            sudo docker ps -aq | xargs -I {} sudo docker rm {} &&
            sudo docker run -d -p 3002:3002 gigihsigap/${{env.APP_NAME}}-media:${{ github.run_number }}
          
      - name: Discord notification
        if: failure()
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Deployment for '${{env.APP_NAME}} - ${{env.ENVIRONMENT}}' FAILED! :x:"

  dev_notification_stage:
    name: Discord notification
    runs-on: ubuntu-latest
    needs: dev_deploy_stage
    steps:
    - name: Discord notification
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
        content: "Successful build for '${{env.APP_NAME}} - ${{env.ENVIRONMENT}}' :white_check_mark:"
    
    - name: Adding markdown
      run: echo '### Deployment :rocket:' >> $GITHUB_STEP_SUMMARY
   